mpi: coll: missing return
Change to void to avoid:
src/mpi/coll/shmem/mvp_shmem_coll.c:1802:1: error: no return statement in function returning non-void [-Werror=return-type]

Signed-off-by: Nicolas Morey <nmorey@suse.com>